# Generated by Django 4.1 on 2022-08-20 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FamiliApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='dia_nacimiento',
        ),
        migrations.AddField(
            model_name='familiar',
            name='ultimo_asado',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
